/**
 * Writes dist/client/_headers after `astro build`.
 *
 * The Content-Security-Policy is generated rather than hand-written because
 * Astro emits a handful of inline <script> and <style> blocks whose contents
 * change whenever the source does. A hand-maintained policy would silently
 * drift out of date and start blocking the site's own JavaScript, so the
 * hashes are recomputed from the built HTML every time.
 *
 * Run automatically by `npm run build`.
 */
import { createHash } from 'node:crypto';
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { join, relative } from 'node:path';

const CLIENT_DIR = new URL('../dist/client/', import.meta.url).pathname;

/** Every .html file under dist/client. */
async function htmlFiles(dir) {
  const found = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) found.push(...(await htmlFiles(full)));
    else if (entry.name.endsWith('.html')) found.push(full);
  }
  return found;
}

const sha256 = (body) => `'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`;

/**
 * Inline <script> and <style> bodies. Tags carrying a src/href are external
 * and covered by 'self' instead. JSON-LD is data, not script, but browsers
 * still apply script-src to it, so it is hashed too.
 */
function collect(html) {
  const scripts = new Set();
  const styles = new Set();

  for (const [, , body] of html.matchAll(/<script(?![^>]*\bsrc=)([^>]*)>([\s\S]*?)<\/script>/g)) {
    scripts.add(sha256(body));
  }
  for (const [, , body] of html.matchAll(/<style([^>]*)>([\s\S]*?)<\/style>/g)) {
    styles.add(sha256(body));
  }
  return { scripts, styles };
}

const files = await htmlFiles(CLIENT_DIR);
const scriptHashes = new Set();
const styleHashes = new Set();
let inlineAttrs = 0;

for (const file of files) {
  const html = await readFile(file, 'utf8');
  const { scripts, styles } = collect(html);
  scripts.forEach((h) => scriptHashes.add(h));
  styles.forEach((h) => styleHashes.add(h));

  // A style="..." attribute cannot be hashed. If one appears, the policy would
  // have to fall back to 'unsafe-inline', so fail loudly instead of quietly
  // weakening the site's own security.
  const attrs = html.match(/\sstyle="/g);
  if (attrs) {
    inlineAttrs += attrs.length;
    console.error(`  inline style attribute in ${relative(CLIENT_DIR, file)}`);
  }
}

if (inlineAttrs > 0) {
  console.error(
    `\nsecurity-headers: ${inlineAttrs} inline style attribute(s) found.\n` +
      `Move them into a class so the CSP can keep banning inline styles.`,
  );
  process.exit(1);
}

const csp = [
  "default-src 'self'",
  `script-src 'self' ${[...scriptHashes].join(' ')}`,
  `style-src 'self' ${[...styleHashes].join(' ')}`,
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "base-uri 'none'",
  "object-src 'none'",
  'upgrade-insecure-requests',
].join('; ');

const headers = `# Generated by scripts/security-headers.mjs — do not edit by hand.
# Regenerated on every \`npm run build\`.

/*
  Content-Security-Policy: ${csp}
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin
  X-Frame-Options: DENY

# Hashed filenames never change contents, so they can be cached forever.
/_astro/*
  Cache-Control: public, max-age=31536000, immutable

# The form endpoint must never be cached or embedded.
/api/*
  Cache-Control: no-store
  X-Robots-Tag: noindex
`;

await writeFile(join(CLIENT_DIR, '_headers'), headers, 'utf8');
console.log(
  `security-headers: ${files.length} pages, ` +
    `${scriptHashes.size} script hash(es), ${styleHashes.size} style hash(es).`,
);
